name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

  package:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create deployment package
      run: |
        zip -r deployable.zip .
        mkdir -p artifact
        mv deployable.zip artifact/

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: deployment-package
        path: artifact/deployable.zip
